### ISSUE TITLE
No such file or directory: 'stats/location_group_mapping.csv'

### ISSUE THREAD

**Issue by hmgene** [CellProfiling/subcell-embed#1]
python main_lightning.py --config configs/MAE-cellS-protS-contrast.yaml

Traceback (most recent call last):
  File "main_lightning.py", line 25, in <module>
    from data.collate_fn import collate_fn_train
  File "/home/oannes/git/subcell-embed/data/__init__.py", line 1, in <module>
    from .dataset import *
  File "/home/oannes/git/subcell-embed/data/dataset.py", line 12, in <module>
    LOCATION_MAP = pd.read_csv("stats/location_group_mapping.csv")
  File "/home/oannes/miniforge3/envs/subcell/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/oannes/miniforge3/envs/subcell/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/oannes/miniforge3/envs/subcell/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/oannes/miniforge3/envs/subcell/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/oannes/miniforge3/envs/subcell/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'stats/location_group_mapping.csv'

**Comment by aktgpt** [comment]
The file location was not updated. Fixed in the latest push.

**Comment by jinzhuangdou** [comment]
where we can get the annotation folder? It seems not shown in the github.

**Comment by hmgene** [comment]
no, please check it again.
Thank you.
-H
