### ISSUE TITLE
utils.agumentation module not found

### ISSUE THREAD

**Issue by jinzhuangdou** [CellProfiling/subcell-embed#4]
(subcell) bash-5.1$  python main_lightning.py --config configs/MAE-cellS-protS-contrast.yaml
Traceback (most recent call last):
  File "/rsrch1/bcb/kchen_group/jdou/ST_explore/subcell-embed/main_lightning.py", line 26, in <module>
    from data.get_datasets import get_datasets
  File "/rsrch1/bcb/kchen_group/jdou/ST_explore/subcell-embed/data/get_datasets.py", line 7, in <module
    from utils.augmentations import (
ModuleNotFoundError: No module named 'utils.augmentations'

**Comment by aktgpt** [comment]
There might be some import issue in running the code since augmentations.py clearly exists in the utils folder.
